web_dev/django/dj4e-samples/chat/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('syntax', TemplateView.as_view(template_name='chat/syntax.html'), 
        name='syntax'),
    path('jsonfun', views.jsonfun, name='jsonfun'),

    path('talk', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]


web_dev/django/dj4e-samples/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

web_dev/django/dj4e-samples/forums/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

# namespace:route_name
app_name='forums'

urlpatterns = [
    path('', views.ForumListView.as_view(), name='all'),
    path('forum/<int:pk>', views.ForumDetailView.as_view(), name='forum_detail'),
    path('forum/create', 
        views.ForumCreateView.as_view(success_url=reverse_lazy('forums:all')), name='forum_create'),
    path('forum/<int:pk>/update', 
        views.ForumUpdateView.as_view(success_url=reverse_lazy('forums:all')), name='forum_update'),
    path('forum/<int:pk>/delete', 
        views.ForumDeleteView.as_view(success_url=reverse_lazy('forums:all')), name='forum_delete'),
    path('forum/<int:pk>/comment', 
        views.CommentCreateView.as_view(), name='forum_comment_create'),
    path('comment/<int:pk>/delete', 
        views.CommentDeleteView.as_view(success_url=reverse_lazy('forums:all')), name='forum_comment_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined


web_dev/django/dj4e-samples/forums/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

class Forum(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(5, "Title must be greater than 5 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, related_name='forums_owned')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, 
        through='Comment', related_name='forum_comments')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'


web_dev/django/dj4e-samples/forums/forms.py

from django import forms
from django.core.exceptions import ValidationError
from django.core import validators

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

web_dev/django/dj4e-samples/forums/views.py
from forums.models import Forum, Comment

from django.views import View
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from django.contrib.auth.mixins import LoginRequiredMixin

from forums.forms import CommentForm
from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

class ForumListView(OwnerListView):
    model = Forum
    template_name = "forums/list.html"

class ForumDetailView(OwnerDetailView):
    model = Forum
    template_name = "forums/detail.html"
    def get(self, request, pk) :
        x = Forum.objects.get(id=pk)
        comments = Comment.objects.filter(forum=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'forum' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)


class ForumCreateView(OwnerCreateView):
    model = Forum
    fields = ['title', 'text']
    template_name = "forums/form.html"

class ForumUpdateView(OwnerUpdateView):
    model = Forum
    fields = ['title', 'text']
    template_name = "forums/form.html"

class ForumDeleteView(OwnerDeleteView):
    model = Forum
    template_name = "forums/delete.html"

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Forum, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, forum=f)
        comment.save()
        return redirect(reverse('forums:forum_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "forums/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        forum = self.object.forum
        return reverse('forums:forum_detail', args=[forum.id])



web_dev/django/dj4e-samples/forums/templates/forums/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'forums:forum_detail' comment.forum.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

web_dev/django/dj4e-samples/forums/templates/forums/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Forum</h1>

<p>Are you sure you want to delete the forum: {{ forum }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

web_dev/django/dj4e-samples/forums/templates/forums/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<h1>
{% if forum.owner == user %}
<span style="float: right;">
<a href="{% url 'forums:forum_update' forum.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'forums:forum_delete' forum.id %}"><i class="fa fa-trash"></i></a>
</span>
{% endif %}
{{ forum.title }}
</h1>
<p>
{{ forum.text }}
</p>
<p>
({{ forum.updated_at|naturaltime }})
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'forums:forum_comment_create' forum.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Forums" onclick="window.location.href='{% url 'forums:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }} 
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'forums:forum_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
{% endblock %}

web_dev/django/dj4e-samples/forums/templates/forums/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'forums:all' %}';return false;">
    <p>
</p>
  </form>
</p>
{% endblock %}

web_dev/django/dj4e-samples/forums/templates/forums/list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Forums</h1>
<p>
{% if forum_list %}
<ul>
  {% for forum in forum_list %}
    <li>
        <a href="{% url 'forums:forum_detail'  forum.id %}">{{ forum.title }}</a>
        {% if forum.owner == user %}
        (<a href="{% url 'forums:forum_update' forum.id %}">Edit</a> |
        <a href="{% url 'forums:forum_delete' forum.id %}">Delete</a>)
        </p>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no forums in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'forums:forum_create' %}">Add an Forum</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'forums:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'forums:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}