web_dev/django/dj4e-samples/chat/urls.py
import os
from django.urls import path, re_path
from django.views.static import serve
from . import views
from django.views.generic import TemplateView

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

app_name='chat'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('syntax', TemplateView.as_view(template_name='chat/syntax.html'), 
        name='syntax'),
    path('jsonfun', views.jsonfun, name='jsonfun'),

    path('talk', views.TalkMain.as_view(), name='talk'),
    path('messages', views.TalkMessages.as_view(), name='messages'),

    # Serve up a local static folder to serve spinner.gif
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'static'), 'show_indexes': True},
        name='static'
    )
]


web_dev/django/dj4e-samples/dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

web_dev/django/dj4e-samples/menu/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name='menu'
urlpatterns = [
    path('', TemplateView.as_view(template_name='menu/main_menu.html'), name='main'),
    path('page1', TemplateView.as_view(template_name='menu/main_menu.html'), name='page1'),
    path('page2', TemplateView.as_view(template_name='menu/main_menu.html'), name='page2'),
    path('page3', TemplateView.as_view(template_name='menu/main_menu.html'), name='page3'),
]

web_dev/django/dj4e-samples/menu/models.py
from django.db import models

# Create your models here.

web_dev/django/dj4e-samples/menu/views.py
from django.views import View

# Create your views here.

web_dev/django/dj4e-samples/menu/templates/menu/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'menu:main' %}">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">

      <!-- Assign output of url function to a variable named
          'xyz' to use in the if statement -->
      {% url 'menu:main' as xyz %}
      <li {% if request.get_full_path == xyz %}class="active"{% endif %}>
          <a href="{% url 'menu:main' %}">Home</a></li>

      {% url 'menu:page1' as abc1 %}
      <li {% if request.get_full_path == abc1 %}class="active"{% endif %}>
          <a href="{% url 'menu:page1' %}">Page 1</a></li>

      {% url 'menu:page2' as abc2 %}
      <li {% if request.get_full_path == abc2 %}class="active"{% endif %}>
          <a href="{% url 'menu:page2' %}">Page 2</a></li>

      <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">Drop Down
          <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'menu:page3' %}">Page 3</a></li>
        </ul>
       </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
      <!-- gravatar depends on app_tags being loaded -->
      <!-- https://brobin.me/blog/2016/07/super-simple-django-gravatar/ -->
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'logout' %}?next={% url 'menu:main' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li><a href="{% url 'login' %}?next={% url 'menu:main' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

web_dev/django/dj4e-samples/menu/templates/menu/main_menu.html
{% extends 'menu/base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}
{% block content %}
<h4>I am the content block in templates/menu/main_menu.html</h4>
<p>
request.path: {{ request.path }}
</p>
{% endblock %}